server:
  port: 80
  servlet:
    session:
      timeout: 30m
spring:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
    servlet:
      load-on-startup: 1
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friends_springboot?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: html5
  messages:
    basename: i18n.messages
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yjy.pojo
  configuration:
    map-underscore-to-camel-case: true
